DROP TABLE IF EXISTS VEHICLE_DETAILS;
 
CREATE TABLE VEHICLE_DETAILS (
  vehicle_id INT AUTO_INCREMENT  PRIMARY KEY,
  vehicle_name VARCHAR(250) NOT NULL,
  manufacturer VARCHAR(250) NOT NULL,
  type VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  engine_no VARCHAR(250) NOT NULL,
  chassis_no VARCHAR(250) NOT NULL,
  status VARCHAR(15) NOT NULL
);

DROP TABLE IF EXISTS USER_DETAILS;
 
CREATE TABLE USER_DETAILS (
  user_id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  phone VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS VEHICLE_SALE_DETAILS;

CREATE TABLE VEHICLE_SALE_DETAILS (
  sale_id INT AUTO_INCREMENT  PRIMARY KEY,
  ownership INT NOT NULL,
  date_of_registration TIMESTAMP NOT NULL,
  date_of_purchase TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiry_date TIMESTAMP NOT NULL,
  user_id INT NOT NULL,
  vehicle_id INT NOT NULL
);

DROP TABLE IF EXISTS MAINTENANCE_DETAILS;

CREATE TABLE MAINTENANCE_DETAILS (
  service_id INT AUTO_INCREMENT  PRIMARY KEY,
  cost INT NOT NULL,
  date TIMESTAMP NOT NULL,
  remarks VARCHAR(250),
  user_id INT NOT NULL,
  vehicle_id INT NOT NULL
);

